/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kylie Halley (https://sketchfab.com/Kyliehalley)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/the-world-map-of-yhilune-baf1dde89ca64be0bc64d105dcb2e4db
Title: The world map of Yhilune
*/
/* eslint-disable */


import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import map from "../../../assets/Img/Model/map.glb";


export function Map(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(map);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        >
          <group
            name="49c263767ebe419b995a79dec1784c3dfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Globe"
                  rotation={[-Math.PI / 2, 0, -0.026]}
                  scale={100}
                >
                  <mesh
                    name="Globe_Material001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Globe_Material001_0.geometry}
                    material={materials["Material.001"]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(map);