/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kavinda.Attanayake (https://sketchfab.com/Kavinda.Attanayake)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-bull-685d34bc87a643289d31c0c1e4072029
Title: Low Poly Bull
*/
/* eslint-disable */
import React from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial, Vector3, Mesh } from "three";
import { GLTF } from "three-stdlib";
import scene from "../../../assets/Img/Model/lowpoly.glb";

export function Model(props) {
  const { nodes, materials } = useGLTF(scene);
  
  return (
    <group {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group position={[0, -0.0572, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.polySurface11_lambert1_0.geometry}
                  material={materials.lambert1}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(scene);