/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: EVA-Stud (https://sketchfab.com/EVAStud)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toy-style-safe-37a3d555a73c4a81a28401fcf710f304
Title: toy-style safe
*/
/* eslint-disable */
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import safe from "../../../assets/Img/Model/safe.glb";


export function Box(props) {
  const { nodes, materials } = useGLTF(safe);
  
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[-79.3, -0.321, 100.15]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_Material003_0.geometry}
            material={materials["Material.003"]}
          />
          <group
            position={[0.793, 0.001, 0.003]}
            rotation={[Math.PI / 2, 0, -1.683]}
            scale={0.321}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle_Material001_0.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle_Material002_0.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle_Material002_0_1.geometry}
              material={materials["Material.002"]}
            />
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material003_0.geometry}
          material={materials["Material.003"]}
          position={[0, 0, 58.224]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[88.772, 0.356, 107.064]}
          scale={14.963}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Material003_0.geometry}
          material={materials["Material.003"]}
          position={[-24.177, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-79.3, -0.321, 100.15]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload(safe);