/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anabir (https://sketchfab.com/Anabir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/egyptian-portal-b0ea24cabd874c4487026838dce85604
Title: Egyptian Portal
*/
/* eslint-disable */
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import portal from "../../../assets/Img/Model/portal.glb";


export function Portall(props) {
  const { nodes, materials } = useGLTF(portal);
  return (
    <group {...props} dispose={null}>
      <group position={[0, 145.533, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arch_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[0, 80.663, -145.533]}
        />
      </group>
      <group
        position={[-103.627, 72.727, -21.884]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[127.46, 0, -21.791]}
        />
      </group>
      <group
        position={[22.187, 39.955, -160.473]}
        rotation={[-Math.PI / 2, 0, 0.436]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stones_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[-3.597, -163.406, -39.955]}
        />
      </group>
      <group
        position={[-24.632, 3.673, -234.713]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object023_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[33.885, -139.365, -62.79]}
        />
      </group>
      <group
        position={[-106.668, 42.469, -19.891]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.831}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object025_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[99.197, 161.326, -154.876]}
        />
      </group>
      <group
        position={[-110.876, -3.921, -19.897]}
        rotation={[-Math.PI / 2, 0, Math.PI / 9]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Round_Stone007_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[131.668, -0.006, 3.921]}
        />
      </group>
      <group
        position={[21.196, 39.955, 152.566]}
        rotation={[-Math.PI / 2, 0, 2.618]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stones001_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[-3.597, -163.406, -39.955]}
        />
      </group>
      <group
        position={[60.172, 11.65, 82.114]}
        rotation={[-1.402, -0.045, -0.258]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object026_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[33.885, -139.365, -62.79]}
        />
      </group>
      <group position={[94.86, -1.66, 42.054]} rotation={[-1.88, 0.155, 2.216]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object027_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[33.885, -139.365, -62.79]}
        />
      </group>
      <group
        position={[-107.266, -1.321, -21.318]}
        rotation={[-Math.PI / 2, 0, Math.PI / 9]}
        scale={[0.608, 0.608, 0.634]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Round_Stone008_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[131.668, -0.006, 3.921]}
        />
      </group>
      <group
        position={[-10.645, -4.179, -135.75]}
        rotation={[-1.028, -0.837, -0.888]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object028_TEXTURE_0.geometry}
          material={materials.TEXTURE}
          position={[33.885, -139.365, -62.79]}
        />
      </group>
      <group
        position={[-104.673, 90.139, -21.792]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.466}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box042_TEXTURE_2_0.geometry}
          material={materials.TEXTURE_2}
          position={[-1.077, 0.446, 0.185]}
        />
      </group>
      <group
        position={[-50.918, 2.2, 151.35]}
        rotation={[-Math.PI / 2, 0, Math.PI / 9]}
        scale={0.466}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box051_TEXTURE_2_0.geometry}
          material={materials.TEXTURE_2}
          position={[-1.077, 0.446, 0.185]}
        />
      </group>
      <group
        position={[-40.177, 2.2, -201.208]}
        rotation={[-Math.PI / 2, 0, -0.087]}
        scale={0.601}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box052_TEXTURE_2_0.geometry}
          material={materials.TEXTURE_2}
          position={[-1.077, 0.446, 0.185]}
        />
      </group>
      <group
        position={[-106.053, 0, -21.911]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.872, 0.872, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Water001_TEXTURE_3_0.geometry}
          material={materials.TEXTURE_3}
          position={[0, 0, -10.012]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line002_TEXTURE_2_0.geometry}
        material={materials.TEXTURE_2}
        position={[0, 5.106, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box034_TEXTURE_2_0.geometry}
        material={materials.TEXTURE_2}
        position={[-26.681, 3.066, -188.351]}
        rotation={[-1.655, 0.023, 1.31]}
        scale={1.213}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box035_TEXTURE_2_0.geometry}
        material={materials.TEXTURE_2}
        position={[-12.627, 10.05, 135.199]}
        rotation={[-1.194, -0.379, -0.759]}
        scale={1.017}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box036_TEXTURE_2_0.geometry}
        material={materials.TEXTURE_2}
        position={[141.598, 2.884, 186.282]}
        rotation={[-1.342, 0.033, -0.945]}
        scale={1.082}
      />
    </group>
  );
}

useGLTF.preload(portal);
